# 
# PSI SS 2023 - Assignment 2
# The code and resources available in this repository are to be used in the scope of the SS course.
#
# Authors: Nuno Antunes <nmsa@dei.uc.pt>
#
version: '3'

services:
  db:
    build: ./postgresql
    container_name: db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
  web:
    build: ./nodejs
    container_name: web
    command: npm run start
    environment:
      DB_HOST: db
    volumes:
      - "./nodejs/src:/usr/src/app/src"
    expose:
      - "3000"
    ports:
      - "8080:3000"
    depends_on:
      - db

      